### ISSUE TITLE
broken as of newest runelite changes

### ISSUE THREAD

**Issue by boxxxxy** [AnkouOSRS/unpotted-reminder#17] opened 2024-05-27 12:31 UTC
alert no longer displayed on screen. I am assuming it's due to the latest osrs changes, and runelite has had to change some stuff to accommodate them.

**Comment by AnkouOSRS** [comment] 2024-07-27 20:31
I can't reproduce this, please check your plugin settings and provide screenshots or additional details if you're still experiencing issues.

**Comment by AnkouOSRS** [comment] 2024-07-27 20:47
Closing but feel free to open a new issue with the additional details if you still have issues

**Closed as completed by AnkouOSRS** 2024-07-27 20:47 UTC
